### ISSUE TITLE
Radix sort

### ISSUE THREAD

**Issue by PizzaLover10** [PizzaLover10/DSA-go#13]
Implement radix sort algorithm

**Comment by pixobia** [comment]
assign me..

**Comment by Mayureshkaulwar** [comment]
please assign to me

**Comment by PizzaLover10** [comment]
@Mayureshkaulwar This issue has been assigned to you, go through the [Contributing Guidelines](https://github.com/PizzaLover10/DSA-go/blob/main/CONTRIBUTING.md) before making a pull request

**Comment by PizzaLover10** [comment]
Solved in #17
