### ISSUE TITLE
Selection sort

### ISSUE THREAD

**Issue by PizzaLover10** [PizzaLover10/DSA-go#2]
Implement selection sort algorithm

**Comment by Dhruv9449** [comment]
Can I be assigned this?

**Comment by PizzaLover10** [comment]
Sure

**Comment by Ash0069** [comment]
Hi @PizzaLover10 please assign this issue to me

**Comment by PizzaLover10** [comment]
Sorry @Ash0069 it was already assigned before

**Comment by PizzaLover10** [comment]
Solved in #11
