### ISSUE TITLE
Quick sort

### ISSUE THREAD

**Issue by PizzaLover10** [PizzaLover10/DSA-go#6]
Implement quick sort algorithm

**Comment by aman6969** [comment]
please assign this to me @PizzaLover10

**Comment by PizzaLover10** [comment]
sure

**Comment by Mayureshkaulwar** [comment]
please assign this to me

**Comment by aman6969** [comment]
i have created PR please merge @PizzaLover10

**Comment by PizzaLover10** [comment]
@aman6969 I don't see any PRs, please recheck and also reference the issue while making the PR

**Comment by aman6969** [comment]
please check your fork @PizzaLover10

**Comment by PizzaLover10** [comment]
Since @aman6969 has used c++ instead of go, @Mayureshkaulwar I am assigning this issue to you

**Comment by aman6969** [comment]
please assign this to me again @PizzaLover10

**Comment by PizzaLover10** [comment]
@aman6969 sorry, @Mayureshkaulwar created a PR that has been merged. You can work on the other issues

**Comment by PizzaLover10** [comment]
Solved in #20
